sudo: true
language: java
jdk:
- oraclejdk8
before_install:
- ulimit -c unlimited -S
after_success:
- bash .travis_after_success.sh
cache:
  directories:
  - "$HOME/.m2"
addons:
  apt:
    packages:
    - oracle-java8-installer
env:
  global:
  - JAVA_OPTS: "'-Xms512m -Xmx2g'"
  - secure: f8UAvGBRY8XrOvyjQPomTi6Q7xWAAn1UOIsrCOX5vlwkNf9iYlyxFTiNbemceclJj904Y+eyYRbH4T9In9BNhDUAumYa9GzqpOdtSMDn3KOYFbInP1SjliZJFDzlbk+cxh5natkbU7l5Md7FfrXEPVvPEBALCyph3oUb1S17vgh7Rm3et34VAm3+kYuUnzQdHd5H6G33rb5oVLIIUB7wRNAqlli0Dn9VsCsbn2W+ZyznYwpfzyjiu4Qxk0DReebyNEhuQWdZnCvQnSJpBb8FOIDPX9lYwVA4T4TPKazAvcwV1YwtBkj/4br2a43EClyFSw4g+WBaY3cIffIfrnV2hGftD9jbTDAJ1KKaBJGJ22ETbTi0E0yOO+pwgBmSc79fCN4y4yv0Y05Kig+hD/NGgB0KGPv6rZRpGQ+u01Y5JmhMBK/ouHpJ2V+D4MafnJTjnPl5rfwhLR9a0d8rUHCOrEPotGUvjI+fUYrk7GnNrwHOdvFHBBRv6mcCws1c4VaFIghf5o8OY3zExUAz5LUuRgw4/yxHbKvpC/QynKdqUABJhS1/VR45czhxydYWqp8LnjqRxiXDawPgqeUNPodz1I5q+t7H4s8IkH1wNlmmd0hm9t3WTKEwU50kACTqt34nD/I4Rjer1BbJUnX00+k5nBpJa9nEF9oNtwaykO2niEU=
